import { cn } from "@/utils";
import "./globals.css";
import { Patrick_Hand } from "next/font/google";
import AppProviders from "./providers";

const patrickHand = Patrick_Hand({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en">
      <body
        className={cn(
          patrickHand.className,
          "container min-h-screen mx-auto py-4"
        )}
      >
        <AppProviders>{children}</AppProviders>
        {modal}
      </body>
    </html>
  );
}
