import { cn } from '@/utils'
import './globals.css'
import { Patrick_Hand as PatrickHand } from 'next/font/google'
import AppProviders from './providers'

const patrickHand = PatrickHand({
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en">
      <body className={cn(patrickHand.className, 'container mx-auto min-h-screen antialiased')}>
        <div className="m-auto max-w-[375px]">
          <AppProviders>{children}</AppProviders>
        </div>
        {modal}
      </body>
    </html>
  )
}
